export const myProjects = [
  {
    projectTitle: "react  & MUI",
    category: ["react", "MUI"],
    imgPath: "./images/1.png",
    desc: "Developed a dashboard using ReactJs and MUI",
    linkPath: "https://od-dashboards.vercel.app/",
    linkGit: "https://github.com/OdaiSamara/E-commerce",
  },
  {
    projectTitle: "react  & MUI",
    category: ["react", "MUI"],
    imgPath: "./images/16.png",
    desc: "Developed an E-Commerce using ReactJs and MUI",
    linkPath: "https://e-commerce-alpha-one-37.vercel.app/",
    linkGit: "https://github.com/OdaiSamara/E-commerce",
  },
  {
    projectTitle: "react & BootStrap ",
    category: ["react", "BootStrap"],
    imgPath: "./images/2.png",
    desc: "Developed a personal portfolio using ReactJs and BootStrap",
    linkPath: "https://od-portfolio-react.vercel.app/",
    linkGit: "https://github.com/OdaiSamara/od-portfolioReact",
  },
  {
    projectTitle: "react & css",
    category: ["react", "css"],
    imgPath: "./images/3.png",
    desc: "Developing a project to add or delete a product using ReactJs and Css",
    linkPath: "https://new-product-rho.vercel.app/",
    linkGit: "https://github.com/OdaiSamara/newProduct",

  },
  {
    projectTitle: "react & css",
    category: ["react", "css"],
    imgPath: "./images/4.png",
    desc: "Developed a loan login interface using ReactJs and Css",
    linkPath: "https://odaisamara.github.io/od-Requesting-A-Loan/",
    linkGit: "https://github.com/OdaiSamara/od-Requesting-A-Loan",
  },
  {
    projectTitle: "Next & Tailwind ",
    category: ["next", "tailwind"],
    imgPath: "./images/5.png",
    desc: "Developed a project using NextJs and Tailwind",
    linkPath: "https://od-ocean.vercel.app/",
    linkGit: "https://github.com/OdaiSamara/od-Ocean",
  },

  {
    projectTitle: "javaScript & JQuery",
    category: ["js", "jq"],
    imgPath: "./images/6.png",
    desc: "Develop a project to generate random passwords using javaScript and JQuery",
    linkPath: "https://odaisamara.github.io/od-RandomPassword/",
    linkGit: "https://github.com/OdaiSamara/od-RandomPassword",
  },
  {
    projectTitle: "javaScript & JQuery",
    category: ["js", "jq"],
    imgPath: "./images/7.png",
    desc: "Developing a project to verify the phone number if it is Sritel or MTN using JavaScript and JQuery",
    linkPath: "https://odaisamara.github.io/od-checkNumber/",
    linkGit: "https://github.com/OdaiSamara/od-checkNumber",
  },
  {
    projectTitle: "javaScript & JQuery",
    category: ["js", "jq"],
    imgPath: "./images/8.png",
    desc: "Developing an interface that contains an input box and a number of buttons that add the word at the beginning of the list and a word at the end of the list, and a way to delete the individual list in the list. Delete the new added elements using JavaScript and JQuery.",
    linkPath: "https://odaisamara.github.io/od-list/",
    linkGit: "https://github.com/OdaiSamara/od-list",
  },
  {
    projectTitle: "javaScript ",
    category: ["js"],
    imgPath: "./images/9.png",
    desc: "Developing a project that creates a new product, deleting a product, modifying a product, deleting a group of products, calculating the value of the product, searching for the product using javaScrpt",
    linkPath: "https://odaisamara.github.io/od-curds/",
    linkGit: "https://github.com/OdaiSamara/od-curds",
  },
  {
    projectTitle: "javaScript ",
    category: ["js"],
    imgPath: "./images/10.png",
    desc: "Memory game development using javaScript",
    linkPath: "https://odaisamara.github.io/od-memorey-game/",
    linkGit: "https://github.com/OdaiSamara/od-memorey-game",
  },
  {
    projectTitle: "javaScript ",
    category: ["js"],
    imgPath: "./images/11.png",
    desc: "XO game development using javaScript",
    linkPath: "https://odaisamara.github.io/od-xo-game/",
    linkGit: "https://github.com/OdaiSamara/od-xo-game",
  },
  {
    projectTitle: "javaScript & bootStrap",
    category: ["js", "bootstrap"],
    imgPath: "./images/12.png",
    desc: "Developing a website for a grill restaurant using JavaScript and BootStrap",
    linkPath: "https://odaisamara.github.io/od-barbecue/",
    linkGit: "https://github.com/OdaiSamara/od-barbecue",
  },
  {
    projectTitle: "javaScript & bootStrap",
    category: ["js", "bootstrap"],
    imgPath: "./images/13.png",
    desc: "Developed a personal profile website using javaScript and BootStrap",
    linkPath: "https://odaisamara.github.io/od-myProfile/",
    linkGit: "https://github.com/OdaiSamara/od-myProfile",
  },
  {
    projectTitle: "html & css ",
    category: ["html", "css"],
    imgPath: "./images/14.png",
    desc: "Developing an animation website using HTML and CSS",
    linkPath: "https://odaisamara.github.io/od-Adventurer/",
    linkGit: "https://github.com/OdaiSamara/od-Adventurer",
  },
  {
    projectTitle: "html & css ",
    category: ["html", "css"],
    imgPath: "./images/15.png",
    desc: "Developing a control panel using Html and Css",
    linkPath: "https://odaisamara.github.io/od-Dashboard/",
    linkGit: "https://github.com/OdaiSamara/od-Dashboard"
  },
];